wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 8192
model:
  desc: null
  value: pna
data:
  desc: null
  value: ''
num_neighbors:
  desc: null
  value:
  - 100
  - 100
lr:
  desc: null
  value: 0.0006116418195373612
n_hidden:
  desc: null
  value: 20
n_gnn_layers:
  desc: null
  value: 2
loss:
  desc: null
  value: ce
w_ce1:
  desc: null
  value: 1.0003967674742307
w_ce2:
  desc: null
  value: 7.077633468006714
dropout:
  desc: null
  value: 0.08340440094051481
final_dropout:
  desc: null
  value: 0.28812979737686323
n_heads:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717354851.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      - 61
      4: 3.9.19
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
